# Generated by Django 3.1 on 2022-01-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220119_1226'),
        ('store', '0015_auto_20201023_1840'),
    ]

    operations = [
    ]
